apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: {{ cert_email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: umeesh
  namespace: default
spec:
  secretName: umeesh-secret
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.umee.sh"
