apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: ceph-csi
data:
  config.json: |-
    [
      {
        "clusterID": "proxmox-ceph",
        "monitors": [
          "192.168.0.150:6789"
        ]
      }
    ]
