[project]
name = "run-ansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "ansible>=11.9.0",
    "ansible-lint>=25.8.2",
]
