apiVersion: apps/v1
kind: Deployment
metadata:
  name: phanpy
  namespace: app-phanpy
  labels:
    app: phanpy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phanpy
  template:
    metadata:
      labels:
        app: phanpy
    spec:
      containers:
        - name: phanpy
          image: localhost:32000/phanpy:2026.01.31.8b98d5a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
